@baseUrl = http://localhost:8000/api
@authToken = {{login.response.body.token}}

### Regisztráció
POST {{baseUrl}}/register
Accept: application/json
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="username"

Teszt Elek2
--boundary
Content-Disposition: form-data; name="email"

teszt2@example.com
--boundary
Content-Disposition: form-data; name="password"

password123
# --boundary
# Content-Disposition: form-data; name="profile_picture"; filename="pfp.jpg"
# Content-Type: image/png

# < ./pfp.jpg
--boundary--

###

### Bejelentkezés
# @name login
POST {{baseUrl}}/login
Accept: application/json
Content-Type: application/json

{
    "email": "teszt@example.com",
    "password": "password123"
}

###

### Kijelentkezés
POST {{baseUrl}}/logout
Accept: application/json
Authorization: Bearer {{authToken}}

###

### Zene feltöltése (Bejelentkezés szükséges)
POST {{baseUrl}}/songs
Accept: application/json
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="title"

Ominozus
--boundary
Content-Disposition: form-data; name="audio"; filename="3_OMINOZUS.mp3"
Content-Type: audio/mpeg

< ./3_OMINOZUS.mp3
--boundary
Content-Disposition: form-data; name="cover"; filename="cover.jpg"
Content-Type: image/jpeg

< ./cover.jpg
--boundary--

###

### Adott felhasználó zenéinek listázása (Bejelentkezés szükséges)
GET {{baseUrl}}/users/1/songs
Accept: application/json
Authorization: Bearer {{authToken}}
###

### Felhasználó lekérdezése ID alapján
GET {{baseUrl}}/users/1
Accept: application/json

###