@baseUrl = http://localhost:8000/api
@authToken = {{login.response.body.token}}

### 1. Regisztráció (Felhasználó létrehozása + Profilkép)
# Megjegyzés: A profilkép elérési útja a gépeden lévő valós fájlra mutasson!
POST {{baseUrl}}/register
Accept: application/json
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="username"

Teszt Elek
--boundary
Content-Disposition: form-data; name="email"

teszt@example.com
--boundary
Content-Disposition: form-data; name="password"

password123
--boundary
Content-Disposition: form-data; name="profile_picture"; filename="pfp.jpg"
Content-Type: image/png

< ./pfp.jpg
--boundary--

###

### 2. Bejelentkezés
# @name login
POST {{baseUrl}}/login
Accept: application/json
Content-Type: application/json

{
    "email": "teszt@example.com",
    "password": "password123"
}

###

### 3. Kijelentkezés
POST {{baseUrl}}/logout
Accept: application/json
Authorization: Bearer {{authToken}}

###

###Zene feltöltése (Bejelentkezés szükséges)
POST {{baseUrl}}/songs
Accept: application/json
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="title"

Ominozus
--boundary
Content-Disposition: form-data; name="audio"; filename="3_OMINOZUS.mp3"
Content-Type: audio/mpeg

< ./3_OMINOZUS.mp3
--boundary
Content-Disposition: form-data; name="cover"; filename="cover.jpg"
Content-Type: image/jpeg

< ./cover.jpg
--boundary--

###

### 4. Adott felhasználó zenéinek listázása (Bejelentkezés szükséges)
GET {{baseUrl}}/users/1/songs
Accept: application/json
Authorization: Bearer {{authToken}}
###
