@baseUrl = http://localhost:8000/api
@authToken = {{login.response.body.token}}

### Regisztráció
POST {{baseUrl}}/register
Accept: application/json
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="username"

Teszt Elek677
--boundary
Content-Disposition: form-data; name="email"

teszt677@example.com
--boundary
Content-Disposition: form-data; name="password"

password123
# --boundary
# Content-Disposition: form-data; name="profile_picture"; filename="pfp.jpg"
# Content-Type: image/png

# < ./pfp.jpg

###

### Bejelentkezés
# @name login
POST {{baseUrl}}/login
Accept: application/json
Content-Type: application/json

{
    "email": "teszt677@example.com",
    "password": "password123"
}

###

### Kijelentkezés
POST {{baseUrl}}/logout
Accept: application/json
Authorization: Bearer {{authToken}}

###

### Zene feltöltése (Bejelentkezés szükséges)
POST {{baseUrl}}/songs
Accept: application/json
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="title"

Ominozusteszt
--boundary
Content-Disposition: form-data; name="audio"; filename="3_OMINOZUS.mp3"
Content-Type: audio/mpeg

< ./3_OMINOZUS.mp3
--boundary
Content-Disposition: form-data; name="cover"; filename="cover.jpg"
Content-Type: image/jpeg

< ./cover.jpg
--boundary--

###

### Adott felhasználó zenéinek listázása (Bejelentkezés szükséges)
GET {{baseUrl}}/users/2/songs
Accept: application/json
Authorization: Bearer {{authToken}}
###

### Felhasználó lekérdezése ID alapján
GET {{baseUrl}}/users/1
Accept: application/json

###

### Album feltöltése zenékkel (Bejelentkezés szükséges)
POST {{baseUrl}}/albums
Accept: application/json
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="title"

Teszt Album 13
--boundary
Content-Disposition: form-data; name="album_cover"; filename="album_cover.jpg"
Content-Type: image/jpeg

< ./cover.jpg
--boundary
Content-Disposition: form-data; name="songs[0][title]"

Elso Szam
--boundary
Content-Disposition: form-data; name="songs[0][audio]"; filename="3_OMINOZUS.mp3"
Content-Type: audio/mpeg

< ./3_OMINOZUS.mp3
--boundary
Content-Disposition: form-data; name="songs[1][title]"

Masodik Szam
--boundary
Content-Disposition: form-data; name="songs[1][audio]"; filename="3_OMINOZUS2.mp3"
Content-Type: audio/mpeg

< ./3_OMINOZUS2.mp3
--boundary
Content-Disposition: form-data; name="songs[2][title]"

Harmadik Szam
--boundary
Content-Disposition: form-data; name="songs[2][audio]"; filename="3_OMINOZUS2.mp3"
Content-Type: audio/mpeg

< ./3_OMINOZUS2.mp3
--boundary

### 1. Zene lejátszása (Alapértelmezett, nincs playlist)
# Ez rögzíti a history-t album_id-val (ha van), de playlist_id nélkül.
GET {{baseUrl}}/songs/1/play
Accept: audio/mpeg