@baseUrl = http://localhost:8000/api
@authToken = {{login.response.body.token}}

### Login
# @name login
POST {{baseUrl}}/login
Accept: application/json
Content-Type: application/json

{
    "email": "csongeto.csongor@students.jedlik.eu",
    "password": "password123"
}

###

### 1. Search album by id
GET http://localhost:8000/api/albums/1
Accept: application/json

###

### Search album by title or user(artist)
GET http://localhost:8000/api/albums
Accept: application/json

###

### Get album by user_id
GET {{baseUrl}}/users/2/albums
Accept: application/json

###

### Get a given amount of random albums
GET http://localhost:8000/api/albums/random?count=3
Accept: application/json

###

### Upload album
POST {{baseUrl}}/albums
Accept: application/json
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="title"

Elek albumja második felvonás
--boundary
Content-Disposition: form-data; name="album_cover"; filename="album_cover.jpg"
Content-Type: image/jpeg

< ./cover.jpg
--boundary
Content-Disposition: form-data; name="songs[0][title]"

Elso Szam1
--boundary
Content-Disposition: form-data; name="songs[0][audio]"; filename="3_OMINOZUS.mp3"
Content-Type: audio/mpeg

< ./3_OMINOZUS.mp3
--boundary
Content-Disposition: form-data; name="songs[1][title]"

Masodik Szam2
--boundary
Content-Disposition: form-data; name="songs[1][audio]"; filename="3_OMINOZUS2.mp3"
Content-Type: audio/mpeg

< ./3_OMINOZUS2.mp3
--boundary
Content-Disposition: form-data; name="songs[2][title]"

Harmadik Szam3
--boundary
Content-Disposition: form-data; name="songs[2][audio]"; filename="3_OMINOZUS2.mp3"
Content-Type: audio/mpeg

< ./3_OMINOZUS2.mp3
--boundary
