@baseUrl = http://localhost:8000/api
@authToken = {{login.response.body.token}}


### Registration
POST {{baseUrl}}/register
Accept: application/json
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="username"

Cs Cs
--boundary
Content-Disposition: form-data; name="email"

csongeto.csongor@students.jedlik.eu
--boundary
Content-Disposition: form-data; name="password"

password123
--boundary
Content-Disposition: form-data; name="profile_picture"; filename="pfp.jpg"
Content-Type: image/png

< ./pfp.jpg
--boundary--

###

### Login
# @name login
POST {{baseUrl}}/login
Accept: application/json
Content-Type: application/json

{
    "email": "csongeto.csongor@students.jedlik.eu",
    "password": "uj_jelszo_123"
}

###

### Logout
POST {{baseUrl}}/logout
Accept: application/json
Authorization: Bearer {{authToken}}

###

### 1. Reset link kérése
POST http://localhost:8000/api/forgot-password
Content-Type: application/json
Accept: application/json

{
    "email": "csongeto.csongor@students.jedlik.eu"
}

### 2. Jelszó módosítása (A tokent az emailből kell kimásolni)
POST http://localhost:8000/api/reset-password
Content-Type: application/json
Accept: application/json

{
    "token": "ec50451eb967b7403732b54567d4ca39186f06416f5c1c2bd1564b1dcac986ef",
    "email": "csongeto.csongor@students.jedlik.eu",
    "password": "uj_jelszo_123",
    "password_confirmation": "uj_jelszo_123"
}
