@baseUrl = http://localhost:8000/api
@baseUrlServer = https://jcloud02.jedlik.eu/csongeto.csongor/public/api
@authToken = {{login.response.body.token}}

### Login
# @name login
POST {{baseUrl}}/login
Accept: application/json
Content-Type: application/json

{
    "email": "teszt@example.com",
    "password": "password123"
}

###

### Get users history's first page
GET {{baseUrl}}/history
Authorization: Bearer {{authToken}}
Accept: application/json

### Get users history's second page
GET {{baseUrl}}/history?page=2
Authorization: Bearer {{authToken}}
Accept: application/json
