@baseUrl = http://localhost:8000/api
@authToken = {{login.response.body.token}}

### Login
# @name login
POST {{baseUrl}}/login
Accept: application/json
Content-Type: application/json

{
    "email": "teszt@example.com",
    "password": "password"
}

###

### Create new playlist
POST http://localhost:8000/api/playlists
Authorization: Bearer {{authToken}}
Accept: application/json
Content-Type: application/json

{
    "title": "Legjobb zenékcscs"
}

###

### Get my playlists
GET http://localhost:8000/api/playlists
Authorization: Bearer {{authToken}}
Accept: application/json
###

### Get playlist by id
GET http://localhost:8000/api/playlists/2
Authorization: Bearer {{authToken}}
Accept: application/json

### Add song to playlist
POST http://localhost:8000/api/playlists/6/songs/1
Authorization: Bearer {{authToken}}
Accept: application/json

###

### Delete playlist
DELETE http://localhost:8000/api/playlists/66
Authorization: Bearer {{authToken}}
Accept: application/json

###

### Delete song from playlist
DELETE http://localhost:8000/api/playlists/6/songs/1
Authorization: Bearer {{authToken}}
Accept: application/json
