@baseUrl = http://localhost:8000/api
@authToken = {{login.response.body.token}}

### Login
# @name login
POST {{baseUrl}}/login
Accept: application/json
Content-Type: application/json

{
    "email": "csongeto.csongor@students.jedlik.eu",
    "password": "password123"
}

###

### Create new playlist
POST http://localhost:8000/api/playlists
Authorization: Bearer {{authToken}}
Accept: application/json
Content-Type: application/json

{
    "title": "Legjobb zenékcscs"
}

###

### Get my playlists
GET http://localhost:8000/api/playlists
Authorization: Bearer {{authToken}}
Accept: application/json
###

### Get playlist by id
GET http://localhost:8000/api/playlists/2
Authorization: Bearer {{authToken}}
Accept: application/json

### Add song to playlist
POST http://localhost:8000/api/playlists/8/songs/4
Authorization: Bearer {{authToken}}
Accept: application/json

###

### Delete playlist
DELETE http://localhost:8000/api/playlists/8
Authorization: Bearer {{authToken}}
Accept: application/json

###

### Delete song from playlist
DELETE http://localhost:8000/api/playlists/4/songs/3
Authorization: Bearer {{authToken}}
Accept: application/json
