@baseUrl = http://localhost:8000/api
@baseUrlServer = https://jcloud02.jedlik.eu/csongeto.csongor/public/api
@authToken = {{login.response.body.token}}

### Login
# @name login
POST {{baseUrl}}/login
Accept: application/json
Content-Type: application/json

{
    "email": "teszt@example.com",
    "password": "password"
}

###

### Create new playlist
POST {{baseUrl}}/playlists
Authorization: Bearer {{authToken}}
Accept: application/json
Content-Type: application/json

{
    "title": "Legjobb zenékcscs"
}

###

### Get my playlists
GET {{baseUrl}}/playlists
Authorization: Bearer {{authToken}}
Accept: application/json
###

### Get playlist by id
GET {{baseUrl}}/playlists/2
Authorization: Bearer {{authToken}}
Accept: application/json

### Add song to playlist
POST {{baseUrl}}/playlists/6/songs/1
Authorization: Bearer {{authToken}}
Accept: application/json

###

### Delete playlist
DELETE {{baseUrl}}/playlists/66
Authorization: Bearer {{authToken}}
Accept: application/json

###

### Delete song from playlist
DELETE {{baseUrl}}/playlists/6/songs/1
Authorization: Bearer {{authToken}}
Accept: application/json
