@baseUrl = http://localhost:8000/api
@baseUrlServer = https://jcloud02.jedlik.eu/csongeto.csongor/public/api
@authToken = {{login.response.body.token}}

### Login
# @name login
POST {{baseUrl}}/login
Accept: application/json
Content-Type: application/json

{
    "email": "teszt@example.com",
    "password": "password"
}

###

### Get users queue (Ordered by position (incrementing))
GET {{baseUrl}}/queue
Authorization: Bearer {{authToken}}
Accept: application/json

### Add song to queue
POST {{baseUrl}}/queue/222
Authorization: Bearer {{authToken}}
Accept: application/json

### Add a chosen amount of songs to queue
POST {{baseUrl}}/queue/store-many
Authorization: Bearer {{authToken}}
Content-Type: application/json
Accept: application/json

{
    "song_ids": [10, 20, 5]
}

### Get queue item based on position
GET {{baseUrl}}/queue/position/1
Authorization: Bearer {{authToken}}

### Move queue item by position
PATCH {{baseUrl}}/queue/move/5/to/5
Authorization: Bearer {{authToken}}
Accept: application/json

### Delete by position
DELETE {{baseUrl}}/queue/position/3
Authorization: Bearer {{authToken}}
Accept: application/json

### Clear my queue
DELETE {{baseUrl}}/queue/clear
Authorization: Bearer {{authToken}}
Accept: application/json
