@baseUrl = http://localhost:8000/api
@authToken = {{login.response.body.token}}

### Login
# @name login
POST {{baseUrl}}/login
Accept: application/json
Content-Type: application/json

{
    "email": "teszt@example.com",
    "password": "password"
}

###

### List songs by user_id
GET {{baseUrl}}/users/211/songs
Accept: application/json
Authorization: Bearer {{authToken}}
###

### Search song by title
GET http://localhost:8000/api/songs?search=impedit
Accept: application/json

###

### Get a given amount of new songs
GET http://localhost:8000/api/songs/new?count=2
Accept: application/json

###

### Get a given amount of random songs
GET http://localhost:8000/api/songs/random?count=2
Accept: application/json

###

### Upload a song
POST {{baseUrl}}/songs
Accept: application/json
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="title"

Zene teszt333
--boundary
Content-Disposition: form-data; name="audio"; filename="3_OMINOZUS.mp3"
Content-Type: audio/mpeg

< ./3_OMINOZUS.mp3
--boundary
Content-Disposition: form-data; name="cover"; filename="cover.jpg"
Content-Type: image/jpeg

< ./cover.jpg
--boundary--

###

### Logging play
POST {{baseUrl}}/songs/2/log-play
Authorization: Bearer {{authToken}}
Accept: application/json
Content-Type: application/json

{
    "playlist_id": 2
}
###

### Update song
POST http://localhost:8000/api/songs/21
Authorization: Bearer {{authToken}}
Accept: application/json
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="title"

New title 2
--boundary
Content-Disposition: form-data; name="cover"; filename="uj_borito.jpg"
Content-Type: image/jpeg

< ./cover.jpg
--boundary--

###

### Get a songs data by id
GET http://localhost:8000/api/songs/28
Accept: application/json

###

### Delete song
DELETE http://localhost:8000/api/songs/21
Authorization: Bearer {{authToken}}
Accept: application/json

###
